# Generated by python -m tools.compile_tests. Do not hand-edit.
testsuite global:
    setup:
        $ _test.transition_timeout = 0.05
        $ _test.timeout = 15.0
        $ _test.screenshot_directory = "reports/screenshots"
        $ preferences.text_cps = 0
        pause until screen "main_menu"
        screenshot "main-menu"
    before testcase:
        $ preferences.afm_enable = False
        $ config.skipping = None
        if not screen "main_menu":
            run MainMenu(confirm=False)
        click id "menu_start"
    teardown:
        exit

testcase route_01:
    pause until "序章 ： 雨夜"
    assert "序章 ： 雨夜"
    pause 0.2
    screenshot "chapter-prologue"
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until "还有一样东西，应该也是你的。"
    pause 0.2
    assert eval not renpy.showing("heroine")
    screenshot "cg-letter"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until "你这次回来，原本只安排了取东西？"
    pause 0.2
    screenshot "branch-s04_open"
    advance until "第四章 ： 今天"
    assert "第四章 ： 今天"
    pause 0.2
    screenshot "chapter-today"
    advance until screen "choice"
    screenshot "revisit-choice"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until screen "ending_card"
    assert eval (last_ending == 'true')
    assert eval (affection == 3)
    assert eval (trust == 4)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_care', 's02_boxes', 's03_letter', 's03_honest', 's03_archive', 's04_gate', 's04_open', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_repair', 's05_departure', 's05_shared_path', 's06_resolution', 's07_true'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-01-true"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_02:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 2)
    assert eval (trust == 3)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_care', 's02_boxes', 's03_letter', 's03_honest', 's03_archive', 's04_gate', 's04_open', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_repair', 's05_departure', 's05_separate_path', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-02-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_03:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until screen "choice"
    click "先约定下一次联系，旧事慢慢谈"
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until screen "ending_card"
    assert eval (last_ending == 'true')
    assert eval (affection == 2)
    assert eval (trust == 3)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_care', 's02_boxes', 's03_letter', 's03_honest', 's03_archive', 's04_gate', 's04_open', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_concrete', 's05_departure', 's05_shared_path', 's06_resolution', 's07_true'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-03-true"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_04:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until screen "choice"
    click "先约定下一次联系，旧事慢慢谈"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 1)
    assert eval (trust == 2)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_care', 's02_boxes', 's03_letter', 's03_honest', 's03_archive', 's04_gate', 's04_open', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_concrete', 's05_departure', 's05_separate_path', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-04-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_05:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until screen "choice"
    click "先收好信，暂时不解释"
    advance until "椅面已经收拾干净，许澄却没有继续往我这边挪。她看了看出口，把纸袋提起来又放下。"
    pause 0.2
    screenshot "branch-s04_reserved"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until screen "ending_card"
    assert eval (last_ending == 'true')
    assert eval (affection == 3)
    assert eval (trust == 2)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_care', 's02_boxes', 's03_letter', 's03_deferred', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_repair', 's05_departure', 's05_shared_path', 's06_resolution', 's07_true'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-05-true"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_06:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until screen "choice"
    click "先收好信，暂时不解释"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 2)
    assert eval (trust == 1)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_care', 's02_boxes', 's03_letter', 's03_deferred', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_repair', 's05_departure', 's05_separate_path', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-06-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_07:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until screen "choice"
    click "先收好信，暂时不解释"
    advance until screen "choice"
    click "先约定下一次联系，旧事慢慢谈"
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 2)
    assert eval (trust == 1)
    assert eval (truth_known == False)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_care', 's02_boxes', 's03_letter', 's03_deferred', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_concrete', 's05_departure', 's05_shared_path', 's06_resolution', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-07-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_08:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until screen "choice"
    click "先收好信，暂时不解释"
    advance until screen "choice"
    click "先约定下一次联系，旧事慢慢谈"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 1)
    assert eval (trust == 0)
    assert eval (truth_known == False)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_care', 's02_boxes', 's03_letter', 's03_deferred', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_concrete', 's05_departure', 's05_separate_path', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-08-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_09:
    advance until screen "choice"
    click "先确认取物时间，把事情办完"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until screen "ending_card"
    assert eval (last_ending == 'true')
    assert eval (affection == 2)
    assert eval (trust == 2)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_business', 's02_boxes', 's03_letter', 's03_honest', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_repair', 's05_departure', 's05_shared_path', 's06_resolution', 's07_true'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-09-true"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_10:
    advance until screen "choice"
    click "先确认取物时间，把事情办完"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 1)
    assert eval (trust == 1)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_business', 's02_boxes', 's03_letter', 's03_honest', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_repair', 's05_departure', 's05_separate_path', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-10-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_11:
    advance until screen "choice"
    click "先确认取物时间，把事情办完"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until screen "choice"
    click "先约定下一次联系，旧事慢慢谈"
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 1)
    assert eval (trust == 1)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_business', 's02_boxes', 's03_letter', 's03_honest', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_concrete', 's05_departure', 's05_shared_path', 's06_resolution', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-11-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_12:
    advance until screen "choice"
    click "先确认取物时间，把事情办完"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until screen "choice"
    click "先约定下一次联系，旧事慢慢谈"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 0)
    assert eval (trust == 0)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_business', 's02_boxes', 's03_letter', 's03_honest', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_concrete', 's05_departure', 's05_separate_path', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-12-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_13:
    advance until screen "choice"
    click "先确认取物时间，把事情办完"
    advance until screen "choice"
    click "先收好信，暂时不解释"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 2)
    assert eval (trust == 0)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_business', 's02_boxes', 's03_letter', 's03_deferred', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_repair', 's05_departure', 's05_shared_path', 's06_resolution', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-13-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_14:
    advance until screen "choice"
    click "先确认取物时间，把事情办完"
    advance until screen "choice"
    click "先收好信，暂时不解释"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 1)
    assert eval (trust == -1)
    assert eval (truth_known == True)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_business', 's02_boxes', 's03_letter', 's03_deferred', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_repair', 's05_departure', 's05_separate_path', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-14-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_15:
    advance until screen "choice"
    click "先确认取物时间，把事情办完"
    advance until screen "choice"
    click "先收好信，暂时不解释"
    advance until screen "choice"
    click "先约定下一次联系，旧事慢慢谈"
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 1)
    assert eval (trust == -1)
    assert eval (truth_known == False)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_business', 's02_boxes', 's03_letter', 's03_deferred', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_concrete', 's05_departure', 's05_shared_path', 's06_resolution', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-15-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_16:
    advance until screen "choice"
    click "先确认取物时间，把事情办完"
    advance until screen "choice"
    click "先收好信，暂时不解释"
    advance until screen "choice"
    click "先约定下一次联系，旧事慢慢谈"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 0)
    assert eval (trust == -2)
    assert eval (truth_known == False)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion', 's02_business', 's02_boxes', 's03_letter', 's03_deferred', 's03_archive', 's04_gate', 's04_reserved', 's04_waiting', 's04_memory', 's04_boundary', 's04_revisit', 's04_concrete', 's05_departure', 's05_separate_path', 's08_normal'])
    assert eval (current_chapter == 'ch05')
    screenshot "route-16-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase save_load_and_restart:
    advance until screen "choice"
    screenshot "first-choice"
    assert eval renpy.get_attributes("heroine") == ('normal',)
    $ renpy.unlink_save("1-1")
    click id "save_open"
    pause until screen "save"
    click id "slot_1"
    assert eval renpy.can_load("1-1")
    click id "game_return"
    pause until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance
    $ trust = -99
    $ renpy.show("heroine angry", at_list=[heroine_position])
    assert eval renpy.get_attributes("heroine") == ("angry",)
    click id "load_open"
    pause until screen "load"
    click id "slot_1"
    if screen "confirm":
        click id "confirm_yes"
    pause until screen "choice"
    assert eval (current_scene == 's02_reunion')
    assert eval (current_chapter == 'ch01')
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion'])
    assert eval (affection == 0 and trust == 0 and not truth_known)
    assert eval renpy.get_attributes("heroine") == ('normal',)
    assert eval renpy.music.get_playing(channel="music") == "audio/bgm/rain_theme.ogg"
    assert eval renpy.music.get_playing(channel="ambient") == "audio/sfx/rain_ambience.ogg"
    run MainMenu(confirm=False)
    click id "menu_start"
    advance until screen "choice"
    assert eval (affection == 0 and trust == 0 and not truth_known)
    assert eval (visited_scenes == ['p00_entry', 's01_arrival', 's01_platform', 's02_reunion'] and current_chapter == 'ch01')

testcase history_preferences_and_audio:
    advance until eval renpy.music.get_playing(channel="voice") is not None
    pause 0.2
    screenshot "first-dialogue"
    click id "history_open"
    assert screen "history"
    screenshot "history"
    click id "game_return"
    click id "preferences_open"
    assert screen "preferences"
    screenshot "settings"
    click id "mute_all"
    assert eval preferences.get_mute("music")
    assert eval preferences.get_mute("sfx")
    assert eval preferences.get_mute("voice")
    click id "mute_all"
    assert eval not preferences.get_mute("music")
    click id "game_return"
    assert eval renpy.music.get_playing(channel="music") is not None
    assert eval renpy.music.get_playing(channel="ambient") is not None

testcase voice_and_display:
    click id "preferences_open"
    click id "display_fullscreen"
    assert eval preferences.fullscreen
    click id "display_window"
    assert eval not preferences.fullscreen
    click id "voice_test"
    assert eval renpy.music.get_playing(channel="voice") == config.sample_voice
    click id "game_return"

testcase auto_and_skip:
    $ preferences.afm_time = 0.1
    $ test_history_length = len(_history_list)
    click id "auto_run"
    assert eval preferences.afm_enable
    pause until eval len(_history_list) > test_history_length
    assert eval len(_history_list) > test_history_length
    click id "auto_run"
    assert eval not preferences.afm_enable
    $ preferences.skip_unseen = False
    click id "preferences_open"
    click id "skip_unseen"
    assert eval preferences.skip_unseen
    click id "game_return"
    click id "skip_run"
    pause until screen "choice"
    assert eval current_scene == 's02_reunion'
    assert eval (affection == 0 and trust == 0 and not truth_known)
    $ config.skipping = None
    $ preferences.afm_time = 15.0
    $ preferences.skip_unseen = False

testcase character_expressions_in_story:
    advance until eval renpy.get_attributes("heroine") == ('smile',)
    pause 0.2
    assert eval renpy.showing("heroine smile")
    screenshot "expression-smile"
    advance until eval renpy.get_attributes("heroine") == ('normal',)
    pause 0.2
    assert eval renpy.showing("heroine normal")
    screenshot "expression-normal"
    advance until eval renpy.get_attributes("heroine") == ('embarrassed',)
    pause 0.2
    assert eval renpy.showing("heroine embarrassed")
    screenshot "expression-embarrassed"
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until eval current_scene == "s03_letter"
    advance
    assert eval not renpy.showing("heroine")
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until eval renpy.get_attributes("heroine") == ('sad',)
    pause 0.2
    assert eval renpy.showing("heroine sad")
    screenshot "expression-sad"
    advance until eval renpy.get_attributes("heroine") == ('angry',)
    pause 0.2
    assert eval renpy.showing("heroine angry")
    screenshot "expression-angry"
    advance until eval renpy.get_attributes("heroine") == ('surprised',)
    pause 0.2
    assert eval renpy.showing("heroine surprised")
    screenshot "expression-surprised"
    advance until eval renpy.get_attributes("heroine") == ('happy',)
    pause 0.2
    assert eval renpy.showing("heroine happy")
    screenshot "expression-happy"

testcase key_voice_and_sound_cues:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until "她从纸袋里抽出一只没有邮票的信封。边角被压平，纸已经有些发黄。"
    pause 0.1
    assert eval renpy.music.get_playing(channel='sound') == 'audio/sfx/paper_rustle.ogg'
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until "……那为什么没给我？"
    pause 0.1
    assert eval renpy.music.get_playing(channel='voice') == 'audio/voice/heroine_q02_honest_l002_v1.ogg'
    advance until "我拿起椅面上的手机，给她发了一个句号。她的屏幕亮起来，头像还是当年那只画得有点歪的猫。"
    pause 0.1
    assert eval renpy.music.get_playing(channel='sound') == 'audio/sfx/message_ping.ogg'

testcase audio_true_ending:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until "还有一样东西，应该也是你的。"
    pause until eval renpy.music.get_playing(channel="music") == "audio/bgm/unspoken_theme.ogg"
    assert eval renpy.music.get_playing(channel='music') == 'audio/bgm/unspoken_theme.ogg'
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until "另一张照片，是什么时候拍的？"
    pause until eval renpy.music.get_playing(channel="music") == "audio/bgm/rain_theme.ogg"
    assert eval renpy.music.get_playing(channel='music') == 'audio/bgm/rain_theme.ogg'
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until "雨小了一些。出口的保安敲了敲玻璃，示意我们该收东西了。"
    pause until eval renpy.music.get_playing(channel="music") == "audio/bgm/next_message_theme.ogg"
    pause until eval renpy.music.get_playing(channel="ambient") == "audio/sfx/rain_light_ambience.ogg"
    assert eval renpy.music.get_playing(channel='music') == 'audio/bgm/next_message_theme.ogg'
    assert eval renpy.music.get_playing(channel='ambient') == 'audio/sfx/rain_light_ambience.ogg'
    advance until screen "choice"
    click "和她一起走，继续聊一会儿"
    advance until "小店的灯还亮着。桌上有水杯、纸巾，和一碟并不特别好吃的饼干。我们坐下，没有谁急着给今晚取名字。"
    pause until eval renpy.music.get_playing(channel="ambient") is None
    assert eval renpy.music.get_playing(channel="ambient") is None
    advance until "嗯。这次记得交给我。"
    pause 0.1
    assert eval renpy.music.get_playing(channel='voice') == 'audio/voice/heroine_s07_true_l010_v1.ogg'
    screenshot "audio-true-voice"
    advance until screen "ending_card"
    pause until eval renpy.music.get_playing(channel="music") is None
    assert eval renpy.music.get_playing(channel="music") is None
    assert eval renpy.music.get_playing(channel="ambient") is None

testcase audio_normal_ending:
    advance until screen "choice"
    click "把干燥的位置让给她，问候近况"
    advance until screen "choice"
    click "告诉她：这封信是我写的"
    advance until screen "choice"
    click "把信里的意思和今天的打算说清楚"
    advance until screen "choice"
    click "今晚先各自回家，改天再联系"
    advance until "手机亮起来。她发来一张旧照片，下面只有一行字。"
    pause 0.1
    assert eval renpy.music.get_playing(channel='sound') == 'audio/sfx/message_ping.ogg'
    advance until "这张没有拍歪。你回去以后，慢慢看。"
    pause 0.1
    assert eval renpy.music.get_playing(channel='voice') == 'audio/voice/heroine_s08_normal_l005_v1.ogg'
    screenshot "audio-normal-voice"
    advance until "雨停了。这个晚上没有给出所有答案，但我们已经重新有了彼此的号码。"
    pause until eval renpy.music.get_playing(channel="ambient") is None
    assert eval renpy.music.get_playing(channel="ambient") is None
    advance until screen "ending_card"
    pause until eval renpy.music.get_playing(channel="music") is None
    assert eval renpy.music.get_playing(channel="music") is None
