# Generated by python -m tools.compile_tests. Do not hand-edit.
testsuite global:
    setup:
        $ _test.transition_timeout = 0.05
        $ _test.timeout = 15.0
        $ _test.screenshot_directory = "reports/screenshots"
        $ preferences.text_cps = 0
        pause until screen "main_menu"
        screenshot "main-menu"
    before testcase:
        if not screen "main_menu":
            run MainMenu(confirm=False)
        click id "menu_start"
    teardown:
        exit

testcase route_01:
    advance until screen "choice"
    click "和她共撑一把伞"
    advance until screen "ending_card"
    assert eval (last_ending == 'true')
    assert eval (affection == 1)
    assert eval (trust == 1)
    assert eval (truth_known == True)
    screenshot "route-01-true"
    click id "ending_return"
    pause until screen "main_menu"

testcase route_02:
    advance until screen "choice"
    click "留下来等雨停"
    advance until screen "ending_card"
    assert eval (last_ending == 'normal')
    assert eval (affection == 0)
    assert eval (trust == -1)
    assert eval (truth_known == False)
    screenshot "route-02-normal"
    click id "ending_return"
    pause until screen "main_menu"

testcase save_load_and_restart:
    advance until screen "choice"
    screenshot "first-choice"
    $ renpy.unlink_save("1-1")
    click id "save_open"
    pause until screen "save"
    click id "slot_1"
    assert eval renpy.can_load("1-1")
    click id "game_return"
    pause until screen "choice"
    click "和她共撑一把伞"
    advance
    $ trust = -99
    click id "load_open"
    pause until screen "load"
    click id "slot_1"
    if screen "confirm":
        click id "confirm_yes"
    pause until screen "choice"
    assert eval (current_scene == 'bootstrap_choice')
    assert eval (affection == 0 and trust == 0 and not truth_known)
    run MainMenu(confirm=False)
    click id "menu_start"
    advance until screen "choice"
    assert eval (affection == 0 and trust == 0 and not truth_known)

testcase history_preferences_and_audio:
    advance
    advance
    click id "history_open"
    assert screen "history"
    screenshot "history"
    click id "game_return"
    click id "preferences_open"
    assert screen "preferences"
    screenshot "settings"
    click id "mute_all"
    click id "mute_all"
    click id "game_return"
    assert eval renpy.music.get_playing(channel="music") is not None
    assert eval renpy.music.get_playing(channel="ambient") is not None
