"""Generate Ren'Py interaction tests from the actual graph's route witnesses."""
import argparse
import json
from tools.story_model import ROOT, load_story, enumerate_routes, scene_lines
from tools.compile_story import quote


def render_tests(story):
    report = enumerate_routes(story)
    if report["errors"]:
        raise ValueError(report["errors"])
    choices = {c["id"]: c for n in story["nodes"] for c in n.get("choices", [])}
    first_choice_scene = next(n["id"] for n in story["nodes"] if "choices" in n)
    first_choice_node = next(n for n in story["nodes"] if n["id"] == first_choice_scene)
    saved_expression = next((line["expression"] for line in reversed(first_choice_node["lines"]) if line.get("expression")), "normal")
    first_path = report["routes"][0]["path"]
    saved_path = first_path[:first_path.index(first_choice_scene) + 1]
    chapters = {c["id"]: c for c in story["chapters"]}
    lines = [
        "# Generated by python -m tools.compile_tests. Do not hand-edit.",
        "testsuite global:",
        "    setup:",
        "        $ _test.transition_timeout = 0.05",
        "        $ _test.timeout = 15.0",
        '        $ _test.screenshot_directory = "reports/screenshots"',
        "        $ preferences.text_cps = 0",
        '        pause until screen "main_menu"',
        '        screenshot "main-menu"',
        "    before testcase:",
        "        $ preferences.afm_enable = False",
        "        $ config.skipping = None",
        '        if not screen "main_menu":',
        "            run MainMenu(confirm=False)",
        '        click id "menu_start"',
        "    teardown:",
        "        exit",
        "",
    ]
    for index, route in enumerate(report["routes"], 1):
        lines += [f"testcase route_{index:02}:"]
        if index == 1:
            title = quote(story["chapters"][0]["title"])
            lines += [f"    pause until {title}", f"    assert {title}",
                      '    pause 0.2', '    screenshot "chapter-prologue"']
        for choice_index, choice_id in enumerate(route["choices"]):
            if index == 1 and choice_index == 1:
                cg_scene = next((n["id"] for n in story["nodes"] if n.get("background") == "unsent_letter"), None)
                if cg_scene:
                    cg_line = next(n["lines"][0]["text"] for n in story["nodes"] if n["id"] == cg_scene)
                    lines += [f"    advance until {quote(cg_line)}", '    pause 0.2',
                              '    assert eval not renpy.showing("heroine")', '    screenshot "cg-letter"']
            if choice_index == 2:
                branch = next(scene for scene in route["path"] if scene in ("s04_open", "s04_reserved"))
                if index in (1, 5):
                    branch_line = next(n["lines"][0]["text"] for n in story["nodes"] if n["id"] == branch)
                    lines += [f"    advance until {quote(branch_line)}",
                              '    pause 0.2', f'    screenshot "branch-{branch}"']
            if index == 1 and choice_id.startswith("q04_"):
                title = quote(chapters["ch04"]["title"])
                lines += [f"    advance until {title}", f"    assert {title}",
                          '    pause 0.2', '    screenshot "chapter-today"',
                          '    advance until screen "choice"', '    screenshot "revisit-choice"']
            lines += ['    advance until screen "choice"', f"    click {quote(choices[choice_id]['text'])}"]
        lines += ['    advance until screen "ending_card"', f"    assert eval (last_ending == {route['ending']!r})"]
        for key, value in route["state"].items():
            lines.append(f"    assert eval ({key} == {value!r})")
        lines += [f"    assert eval (visited_scenes == {route['path']!r})",
                  f"    assert eval (current_chapter == {story['nodes'][-1]['chapter']!r})"]
        lines += [f'    screenshot "route-{index:02}-{route["ending"]}"', '    click id "ending_return"', '    pause until screen "main_menu"', ""]
    lines += [
        "testcase save_load_and_restart:",
        '    advance until screen "choice"',
        '    screenshot "first-choice"',
        f'    assert eval renpy.get_attributes("heroine") == ({saved_expression!r},)',
        '    $ renpy.unlink_save("1-1")',
        '    click id "save_open"',
        '    pause until screen "save"',
        '    click id "slot_1"',
        '    assert eval renpy.can_load("1-1")',
        '    click id "game_return"',
        '    pause until screen "choice"',
        f"    click {quote(choices[report['routes'][0]['choices'][0]]['text'])}",
        '    advance',
        '    $ trust = -99',
        '    $ renpy.show("heroine angry", at_list=[heroine_position])',
        '    assert eval renpy.get_attributes("heroine") == ("angry",)',
        '    click id "load_open"',
        '    pause until screen "load"',
        '    click id "slot_1"',
        '    if screen "confirm":',
        '        click id "confirm_yes"',
        '    pause until screen "choice"',
        f"    assert eval (current_scene == {first_choice_scene!r})",
        f"    assert eval (current_chapter == {first_choice_node['chapter']!r})",
        f"    assert eval (visited_scenes == {saved_path!r})",
        '    assert eval (affection == 0 and trust == 0 and not truth_known)',
        f'    assert eval renpy.get_attributes("heroine") == ({saved_expression!r},)',
        '    assert eval renpy.music.get_playing(channel="music") == "audio/bgm/rain_theme.ogg"',
        '    assert eval renpy.music.get_playing(channel="ambient") == "audio/sfx/rain_ambience.ogg"',
        '    run MainMenu(confirm=False)',
        '    click id "menu_start"',
        '    advance until screen "choice"',
        '    assert eval (affection == 0 and trust == 0 and not truth_known)',
        f"    assert eval (visited_scenes == {saved_path!r} and current_chapter == {first_choice_node['chapter']!r})",
        '',
        'testcase history_preferences_and_audio:',
        '    advance until eval renpy.music.get_playing(channel="voice") is not None',
        '    pause 0.2',
        '    screenshot "first-dialogue"',
        '    click id "history_open"',
        '    assert screen "history"',
        '    screenshot "history"',
        '    click id "game_return"',
        '    click id "preferences_open"',
        '    assert screen "preferences"',
        '    screenshot "settings"',
        '    click id "mute_all"',
        '    assert eval preferences.get_mute("music")',
        '    assert eval preferences.get_mute("sfx")',
        '    assert eval preferences.get_mute("voice")',
        '    click id "mute_all"',
        '    assert eval not preferences.get_mute("music")',
        '    click id "game_return"',
        '    assert eval renpy.music.get_playing(channel="music") is not None',
        '    assert eval renpy.music.get_playing(channel="ambient") is not None',
        '',
        'testcase voice_and_display:',
        '    click id "preferences_open"',
        '    click id "display_fullscreen"',
        '    assert eval preferences.fullscreen',
        '    click id "display_window"',
        '    assert eval not preferences.fullscreen',
        '    click id "voice_test"',
        '    assert eval renpy.music.get_playing(channel="voice") == config.sample_voice',
        '    click id "game_return"',
        '',
        'testcase auto_and_skip:',
        '    $ preferences.afm_time = 0.1',
        '    $ test_history_length = len(_history_list)',
        '    click id "auto_run"',
        '    assert eval preferences.afm_enable',
        '    pause until eval len(_history_list) > test_history_length',
        '    assert eval len(_history_list) > test_history_length',
        '    click id "auto_run"',
        '    assert eval not preferences.afm_enable',
        '    $ preferences.skip_unseen = False',
        '    click id "preferences_open"',
        '    click id "skip_unseen"',
        '    assert eval preferences.skip_unseen',
        '    click id "game_return"',
        '    click id "skip_run"',
        '    pause until screen "choice"',
        f"    assert eval current_scene == {first_choice_scene!r}",
        '    assert eval (affection == 0 and trust == 0 and not truth_known)',
        '    $ config.skipping = None',
        '    $ preferences.afm_time = 15.0',
        '    $ preferences.skip_unseen = False',
        '',
    ]
    lines += ['testcase character_expressions_in_story:']
    # Follow the actual dialogue: first meeting, old photo, then the conversation.
    for expression in ("smile", "normal", "embarrassed"):
        lines += [
            f'    advance until eval renpy.get_attributes("heroine") == ({expression!r},)',
            '    pause 0.2',
            f'    assert eval renpy.showing("heroine {expression}")',
            f'    screenshot "expression-{expression}"',
        ]
    lines += [
        '    advance until screen "choice"',
        f"    click {quote(choices[report['routes'][0]['choices'][0]]['text'])}",
        '    advance until eval current_scene == "s03_letter"',
        '    advance',
        '    assert eval not renpy.showing("heroine")',
        '    advance until screen "choice"',
        f"    click {quote(choices[report['routes'][0]['choices'][1]]['text'])}",
    ]
    for expression in ("sad", "angry", "surprised", "happy"):
        lines += [
            f'    advance until eval renpy.get_attributes("heroine") == ({expression!r},)',
            '    pause 0.2',
            f'    assert eval renpy.showing("heroine {expression}")',
            f'    screenshot "expression-{expression}"',
        ]
    lines.append("")
    dialogue = {line['id']: line for node in story['nodes'] for line in scene_lines(node)}
    recordings = {voice['voice_id']: voice['file'] for voice in json.loads((ROOT / 'game/data/voice_manifest.json').read_text(encoding='utf-8'))['voices']}

    def at_line(identity):
        return f'    advance until {quote(dialogue[identity]["text"])}'

    def choose(identity):
        return ['    advance until screen "choice"', f'    click {quote(choices[identity]["text"])}']

    def playing(channel, file):
        return f'    assert eval renpy.music.get_playing(channel={channel!r}) == {file!r}'

    lines += ['testcase key_voice_and_sound_cues:'] + choose('q01_care')
    lines += [at_line('s03_letter_l002'), '    pause 0.1', playing('sound', 'audio/sfx/paper_rustle.ogg')]
    lines += choose('q02_honest')
    lines += [at_line('q02_honest_l002'), '    pause 0.1',
              playing('voice', recordings[dialogue['q02_honest_l002']['voice']]),
              at_line('s04_waiting_l019'), '    pause 0.1', playing('sound', 'audio/sfx/message_ping.ogg'), '']

    lines += ['testcase audio_true_ending:'] + choose('q01_care')
    lines += [at_line('s03_letter_l001'),
              '    pause until eval renpy.music.get_playing(channel="music") == "audio/bgm/unspoken_theme.ogg"',
              playing('music', 'audio/bgm/unspoken_theme.ogg')]
    lines += choose('q02_honest')
    lines += [at_line('s04_memory_l001'),
              '    pause until eval renpy.music.get_playing(channel="music") == "audio/bgm/rain_theme.ogg"',
              playing('music', 'audio/bgm/rain_theme.ogg')]
    lines += choose('q04_revisit')
    lines += [at_line('s05_departure_l001'),
              '    pause until eval renpy.music.get_playing(channel="music") == "audio/bgm/next_message_theme.ogg"',
              '    pause until eval renpy.music.get_playing(channel="ambient") == "audio/sfx/rain_light_ambience.ogg"',
              playing('music', 'audio/bgm/next_message_theme.ogg'),
              playing('ambient', 'audio/sfx/rain_light_ambience.ogg')]
    lines += choose('q03_walk')
    lines += [at_line('s07_true_l006'), '    pause until eval renpy.music.get_playing(channel="ambient") is None',
              '    assert eval renpy.music.get_playing(channel="ambient") is None',
              at_line('s07_true_l010'), '    pause 0.1',
              playing('voice', recordings[dialogue['s07_true_l010']['voice']]),
              '    screenshot "audio-true-voice"',
              '    advance until screen "ending_card"',
              '    pause until eval renpy.music.get_playing(channel="music") is None',
              '    assert eval renpy.music.get_playing(channel="music") is None',
              '    assert eval renpy.music.get_playing(channel="ambient") is None', '']

    lines += ['testcase audio_normal_ending:'] + choose('q01_care') + choose('q02_honest') + choose('q04_revisit') + choose('q03_leave')
    lines += [at_line('s08_normal_l004'), '    pause 0.1', playing('sound', 'audio/sfx/message_ping.ogg'),
              at_line('s08_normal_l005'), '    pause 0.1',
              playing('voice', recordings[dialogue['s08_normal_l005']['voice']]),
              '    screenshot "audio-normal-voice"',
              at_line('s08_normal_l010'), '    pause until eval renpy.music.get_playing(channel="ambient") is None',
              '    assert eval renpy.music.get_playing(channel="ambient") is None',
              '    advance until screen "ending_card"',
              '    pause until eval renpy.music.get_playing(channel="music") is None',
              '    assert eval renpy.music.get_playing(channel="music") is None', '']
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render_tests(load_story())
    path = ROOT / "game/testcases.rpy"
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit("Stale generated interaction tests")
    else:
        path.write_text(content, encoding="utf-8")
    print("Interaction tests are current." if args.check else "Interaction tests generated.")


if __name__ == "__main__":
    main()
