"""Generate Ren'Py interaction tests from the actual graph's route witnesses."""
import argparse
from tools.story_model import ROOT, load_story, enumerate_routes
from tools.compile_story import quote


def render_tests(story):
    report = enumerate_routes(story)
    if report["errors"]:
        raise ValueError(report["errors"])
    choices = {c["id"]: c for n in story["nodes"] for c in n.get("choices", [])}
    first_choice_scene = next(n["id"] for n in story["nodes"] if "choices" in n)
    lines = [
        "# Generated by python -m tools.compile_tests. Do not hand-edit.",
        "testsuite global:",
        "    setup:",
        "        $ _test.transition_timeout = 0.05",
        "        $ _test.timeout = 15.0",
        "        $ preferences.text_cps = 0",
        '        pause until screen "main_menu"',
        '        screenshot "main-menu"',
        "    before testcase:",
        '        if not screen "main_menu":',
        "            run MainMenu(confirm=False)",
        '        click "开始游戏"',
        "    teardown:",
        "        exit",
        "",
    ]
    for index, route in enumerate(report["routes"], 1):
        lines += [f"testcase route_{index:02}:"]
        for choice_id in route["choices"]:
            lines += ['    advance until screen "choice"', f"    click {quote(choices[choice_id]['text'])}"]
        lines += ['    advance until screen "ending_card"', f"    assert eval (last_ending == {route['ending']!r})"]
        for key, value in route["state"].items():
            lines.append(f"    assert eval ({key} == {value!r})")
        lines += [f'    screenshot "route-{index:02}-{route["ending"]}"', '    click id "ending_return"', '    pause until screen "main_menu"', ""]
    lines += [
        "testcase save_load_and_restart:",
        '    advance until screen "choice"',
        '    screenshot "first-choice"',
        '    $ renpy.unlink_save("1-1")',
        '    click "保存"',
        '    pause until screen "save"',
        '    click id "slot_1"',
        '    assert eval renpy.can_load("1-1")',
        '    click "返回"',
        '    pause until screen "choice"',
        f"    click {quote(choices[report['routes'][0]['choices'][0]]['text'])}",
        '    advance',
        '    $ trust = -99',
        '    click "读取"',
        '    pause until screen "load"',
        '    click id "slot_1"',
        '    if screen "confirm":',
        '        click "是"',
        '    pause until screen "choice"',
        f"    assert eval (current_scene == {first_choice_scene!r})",
        '    assert eval (affection == 0 and trust == 0 and not truth_known)',
        '    run MainMenu(confirm=False)',
        '    click "开始游戏"',
        '    advance until screen "choice"',
        '    assert eval (affection == 0 and trust == 0 and not truth_known)',
        '',
        'testcase history_preferences_and_audio:',
        '    advance',
        '    advance',
        '    click "历史"',
        '    assert screen "history"',
        '    screenshot "history"',
        '    click "返回"',
        '    click "设置"',
        '    assert screen "preferences"',
        '    screenshot "settings"',
        '    click "静音"',
        '    click "静音"',
        '    click "返回"',
        '    assert eval renpy.music.get_playing(channel="music") is not None',
        '    assert eval renpy.music.get_playing(channel="ambient") is not None',
        '',
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render_tests(load_story())
    path = ROOT / "game/testcases.rpy"
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit("Stale generated interaction tests")
    else:
        path.write_text(content, encoding="utf-8")
    print("Interaction tests are current." if args.check else "Interaction tests generated.")


if __name__ == "__main__":
    main()
