"""Generate Ren'Py interaction tests from the actual graph's route witnesses."""
import argparse
from tools.story_model import ROOT, load_story, enumerate_routes
from tools.compile_story import quote


def render_tests(story):
    report = enumerate_routes(story)
    if report["errors"]:
        raise ValueError(report["errors"])
    choices = {c["id"]: c for n in story["nodes"] for c in n.get("choices", [])}
    first_choice_scene = next(n["id"] for n in story["nodes"] if "choices" in n)
    first_choice_node = next(n for n in story["nodes"] if n["id"] == first_choice_scene)
    saved_expression = next((line["expression"] for line in reversed(first_choice_node["lines"]) if line.get("expression")), "normal")
    lines = [
        "# Generated by python -m tools.compile_tests. Do not hand-edit.",
        "testsuite global:",
        "    setup:",
        "        $ _test.transition_timeout = 0.05",
        "        $ _test.timeout = 15.0",
        '        $ _test.screenshot_directory = "reports/screenshots"',
        "        $ preferences.text_cps = 0",
        '        pause until screen "main_menu"',
        '        screenshot "main-menu"',
        "    before testcase:",
        "        $ preferences.afm_enable = False",
        "        $ config.skipping = None",
        '        if not screen "main_menu":',
        "            run MainMenu(confirm=False)",
        '        click id "menu_start"',
        "    teardown:",
        "        exit",
        "",
    ]
    for index, route in enumerate(report["routes"], 1):
        lines += [f"testcase route_{index:02}:"]
        for choice_index, choice_id in enumerate(route["choices"]):
            if index == 1 and choice_index == 1:
                cg_scene = next((n["id"] for n in story["nodes"] if n.get("background") == "unsent_letter"), None)
                if cg_scene:
                    lines += [f"    advance until eval current_scene == {cg_scene!r}", '    advance', '    screenshot "cg-letter"']
            lines += ['    advance until screen "choice"', f"    click {quote(choices[choice_id]['text'])}"]
        lines += ['    advance until screen "ending_card"', f"    assert eval (last_ending == {route['ending']!r})"]
        for key, value in route["state"].items():
            lines.append(f"    assert eval ({key} == {value!r})")
        lines += [f'    screenshot "route-{index:02}-{route["ending"]}"', '    click id "ending_return"', '    pause until screen "main_menu"', ""]
    lines += [
        "testcase save_load_and_restart:",
        '    advance until screen "choice"',
        '    screenshot "first-choice"',
        f'    assert eval renpy.get_attributes("heroine") == ({saved_expression!r},)',
        '    $ renpy.unlink_save("1-1")',
        '    click id "save_open"',
        '    pause until screen "save"',
        '    click id "slot_1"',
        '    assert eval renpy.can_load("1-1")',
        '    click id "game_return"',
        '    pause until screen "choice"',
        f"    click {quote(choices[report['routes'][0]['choices'][0]]['text'])}",
        '    advance',
        '    $ trust = -99',
        '    $ renpy.show("heroine angry", at_list=[heroine_position])',
        '    assert eval renpy.get_attributes("heroine") == ("angry",)',
        '    click id "load_open"',
        '    pause until screen "load"',
        '    click id "slot_1"',
        '    if screen "confirm":',
        '        click id "confirm_yes"',
        '    pause until screen "choice"',
        f"    assert eval (current_scene == {first_choice_scene!r})",
        '    assert eval (affection == 0 and trust == 0 and not truth_known)',
        f'    assert eval renpy.get_attributes("heroine") == ({saved_expression!r},)',
        '    run MainMenu(confirm=False)',
        '    click id "menu_start"',
        '    advance until screen "choice"',
        '    assert eval (affection == 0 and trust == 0 and not truth_known)',
        '',
        'testcase history_preferences_and_audio:',
        '    advance until eval renpy.music.get_playing(channel="voice") is not None',
        '    screenshot "first-dialogue"',
        '    click id "history_open"',
        '    assert screen "history"',
        '    screenshot "history"',
        '    click id "game_return"',
        '    click id "preferences_open"',
        '    assert screen "preferences"',
        '    screenshot "settings"',
        '    click id "mute_all"',
        '    assert eval preferences.get_mute("music")',
        '    click id "mute_all"',
        '    assert eval not preferences.get_mute("music")',
        '    click id "game_return"',
        '    assert eval renpy.music.get_playing(channel="music") is not None',
        '    assert eval renpy.music.get_playing(channel="ambient") is not None',
        '',
        'testcase voice_and_display:',
        '    click id "preferences_open"',
        '    click id "display_fullscreen"',
        '    assert eval preferences.fullscreen',
        '    click id "display_window"',
        '    assert eval not preferences.fullscreen',
        '    click id "voice_test"',
        '    assert eval renpy.music.get_playing(channel="voice") == config.sample_voice',
        '    click id "game_return"',
        '',
        'testcase auto_and_skip:',
        '    $ preferences.afm_time = 0.1',
        '    $ test_history_length = len(_history_list)',
        '    click id "auto_run"',
        '    assert eval preferences.afm_enable',
        '    pause until eval len(_history_list) > test_history_length',
        '    assert eval len(_history_list) > test_history_length',
        '    click id "auto_run"',
        '    assert eval not preferences.afm_enable',
        '    $ preferences.skip_unseen = False',
        '    click id "preferences_open"',
        '    click id "skip_unseen"',
        '    assert eval preferences.skip_unseen',
        '    click id "game_return"',
        '    click id "skip_run"',
        '    pause until screen "choice"',
        f"    assert eval current_scene == {first_choice_scene!r}",
        '    assert eval (affection == 0 and trust == 0 and not truth_known)',
        '    $ config.skipping = None',
        '    $ preferences.afm_time = 15.0',
        '    $ preferences.skip_unseen = False',
        '',
    ]
    lines += ['testcase character_expressions_in_story:']
    # Follow the actual dialogue: first meeting, old photo, then the conversation.
    for expression in ("normal", "smile", "embarrassed"):
        lines += [
            f'    advance until eval renpy.get_attributes("heroine") == ({expression!r},)',
            '    pause 0.2',
            f'    assert eval renpy.showing("heroine {expression}")',
            f'    screenshot "expression-{expression}"',
        ]
    lines += [
        '    advance until screen "choice"',
        f"    click {quote(choices[report['routes'][0]['choices'][0]]['text'])}",
        '    advance until eval current_scene == "s03_letter"',
        '    advance',
        '    assert eval not renpy.showing("heroine")',
        '    advance until screen "choice"',
        f"    click {quote(choices[report['routes'][0]['choices'][1]]['text'])}",
    ]
    for expression in ("sad", "angry", "surprised", "happy"):
        lines += [
            f'    advance until eval renpy.get_attributes("heroine") == ({expression!r},)',
            '    pause 0.2',
            f'    assert eval renpy.showing("heroine {expression}")',
            f'    screenshot "expression-{expression}"',
        ]
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render_tests(load_story())
    path = ROOT / "game/testcases.rpy"
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit("Stale generated interaction tests")
    else:
        path.write_text(content, encoding="utf-8")
    print("Interaction tests are current." if args.check else "Interaction tests generated.")


if __name__ == "__main__":
    main()
