"""Compile structured scenes into ordinary Ren'Py DSL; no custom runtime."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
from tools.story_model import ROOT, load_story, enumerate_routes


def quote(text):
    # Escape Ren'Py substitutions and text tags in authored prose.
    return json.dumps(text.replace("[", "[[").replace("{", "{{"), ensure_ascii=False)


def condition_expression(when):
    parts = []
    for key, rule in when.items():
        if isinstance(rule, dict):
            for op, value in rule.items():
                parts.append(f"{key} {'>=' if op == 'gte' else '=='} {value!r}")
        else:
            parts.append(f"{key} == {rule!r}")
    return " and ".join(parts) or "True"


def render_story(story, assets, voices):
    result = enumerate_routes(story)
    if result["errors"]:
        raise ValueError("\n".join(result["errors"]))
    by_asset = {a["id"]: a for a in assets}
    by_voice = {v["voice_id"]: v for v in voices}
    digest = hashlib.sha256(json.dumps(story, ensure_ascii=False, sort_keys=True).encode()).hexdigest()
    lines = ["# Generated by python -m tools.compile_story; edit game/data/story.json.", f"# Story SHA-256: {digest}", "", "label start:"]
    for k, v in story["initial_state"].items():
        lines.append(f"    $ {k} = {v!r}")
    lines += ['    $ last_ending = ""', '    $ current_chapter = ""', '    $ visited_scenes = []', f"    jump {story['entry']}", ""]
    chapter_entries = {c["entry"]: c["title"] for c in story["chapters"]}
    for node in story["nodes"]:
        lines += [f"label {node['id']}:", f"    $ current_scene = {quote(node['id'])}",
                  f"    $ current_chapter = {quote(node['chapter'])}", f"    $ visited_scenes.append({quote(node['id'])})"]
        if node["id"] in chapter_entries:
            lines += ["    scene black with dissolve", f"    centered {quote(chapter_entries[node['id']])}"]
        if node.get("clear_scene"):
            lines.append("    scene black with dissolve")
        if node.get("background"):
            lines.append(f"    scene expression {quote(by_asset[node['background']]['file'])} with dissolve")
        if node.get("sprite"):
            lines.append(f"    show heroine {node['sprite']} at heroine_position with dissolve")
        if node.get("bgm"):
            lines.append(f"    play music {quote(by_asset[node['bgm']]['file'])} fadein 1.0")
        if node.get("ambient"):
            lines.append(f"    play ambient {quote(by_asset[node['ambient']]['file'])} fadein 1.0")
        for line in node.get("lines", []):
            if line.get("expression"):
                lines.append(f"    show heroine {line['expression']} at heroine_position")
            if line.get("voice"):
                lines.append(f"    voice {quote(by_voice[line['voice']]['file'])}")
            speaker = "" if line["speaker"] == "n" else line["speaker"] + " "
            lines.append(f"    {speaker}{quote(line['text'])}")
        if "ending" in node:
            lines += [f"    $ last_ending = {quote(node['ending'])}", "    stop music fadeout 2.0", "    stop ambient fadeout 2.0", f"    call screen ending_card({quote(node['ending_title'])})", "    return"]
        elif "choices" in node:
            lines.append("    menu:")
            for c in node["choices"]:
                lines.append(f"        {quote(c['text'])}:")
                for k, v in c["effects"].items():
                    lines.append(f"            $ {k} {'=' if type(v) is bool else '+='} {v!r}")
                for response in c.get("response", []):
                    if response.get("expression"):
                        lines.append(f"            show heroine {response['expression']} at heroine_position")
                    if response.get("voice"):
                        lines.append(f"            voice {quote(by_voice[response['voice']]['file'])}")
                    speaker = "" if response["speaker"] == "n" else response["speaker"] + " "
                    lines.append(f"            {speaker}{quote(response['text'])}")
                lines.append(f"            jump {c['next']}")
        elif "routes" in node:
            for i, r in enumerate(node["routes"]):
                if not r.get("when"):
                    lines.append("    else:")
                else:
                    lines.append(f"    {'if' if i == 0 else 'elif'} {condition_expression(r['when'])}:")
                lines.append(f"        jump {r['next']}")
        else:
            lines.append(f"    jump {node['next']}")
        lines.append("")
    images = ["# Generated from asset_manifest.json."]
    for a in assets:
        if a["type"] == "sprite":
            images.append(f"image heroine {a['expression']} = {quote(a['file'])}")
    return "\n".join(lines) + "\n", "\n".join(images) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true", help="Fail if generated scripts are stale")
    args = p.parse_args()
    assets = json.loads((ROOT / "game/data/asset_manifest.json").read_text(encoding="utf-8"))["assets"]
    voices = json.loads((ROOT / "game/data/voice_manifest.json").read_text(encoding="utf-8"))["voices"]
    outputs = render_story(load_story(), assets, voices)
    for path, content in zip([ROOT / "game/script/story_generated.rpy", ROOT / "game/script/images_generated.rpy"], outputs):
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale generated script: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("Ren'Py scripts are current." if args.check else "Ren'Py scripts generated.")


if __name__ == "__main__":
    main()
