"""Bind the native extras room to canonical, story-used assets."""
import argparse
import json
from tools.story_model import ROOT, load_story

IMAGE_TITLES = (
    ('station', '雨夜站台'),
    ('station_exit_covered', '屋檐下'),
    ('station_exit_after_rain', '雨后的出口'),
    ('nearby_cafe', '街角咖啡馆'),
    ('unsent_letter', '未寄出的信'),
)
MUSIC_TITLES = (
    ('rain_theme', '雨夜'),
    ('unspoken_theme', '未说出口'),
    ('next_message_theme', '下一条消息'),
)

def render_extras(story, assets):
    by_id = {a['id']: a for a in assets}
    images, music = [], []
    used_images = {n.get('background') for n in story['nodes']}
    used_music = {n.get('bgm') for n in story['nodes']}
    for identity, title in IMAGE_TITLES:
        asset = by_id[identity]
        if asset['type'] not in ('background', 'cg') or identity not in used_images:
            raise ValueError('Extras image is not a story-used background or CG: '+identity)
        images.append((identity, title, asset['file']))
    for identity, title in MUSIC_TITLES:
        asset = by_id[identity]
        if asset.get('audio_role') != 'bgm' or identity not in used_music:
            raise ValueError('Extras music is not a story-used BGM: '+identity)
        music.append((identity, title, asset['file'], round(asset['audio']['duration_seconds'])))
    return '# Generated by python -m tools.compile_extras; asset_manifest.json is canonical.\n' + \
        f'define -1 extras_images = {tuple(images)!r}\n' + \
        f'define -1 extras_music = {tuple(music)!r}\n'

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    assets = json.loads((ROOT/'game/data/asset_manifest.json').read_text(encoding='utf-8'))['assets']
    content = render_extras(load_story(), assets)
    path = ROOT/'game/script/extras_generated.rpy'
    if args.check:
        if not path.is_file() or path.read_text(encoding='utf-8') != content:
            raise SystemExit('Stale generated extras bindings')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8')
    print('Extras bindings are current.' if args.check else 'Extras bindings generated.')

if __name__ == '__main__':
    main()
