# Generated by python -m tools.compile_story; edit game/data/story.json.
# Story SHA-256: 9c686f914c85223e805321c82c31629f5d98604c9263242acb81407a770479c6

label start:
    $ affection = 0
    $ trust = 0
    $ truth_known = False
    $ last_ending = ""
    jump s01_arrival

label s01_arrival:
    $ current_scene = "s01_arrival"
    scene expression "backgrounds/station_rain.png" with dissolve
    show heroine normal at heroine_position with dissolve
    play music "audio/bgm/rain_theme.ogg" fadein 1.0
    play ambient "audio/sfx/rain_ambience.ogg" fadein 1.0
    "雨从车站的铁皮檐边落下来，连成一层薄薄的帘。路灯照着停运告示，也照着我已经湿透的鞋尖。"
    "手机上的网约车排队数从十二变成十三。我把它收进口袋，沿着熟悉的柱子往里走。"
    "三年前，这个时候的站台会很吵。今天，只有雨点撞在轨道上的声音。"
    "旧寄存柜的号码还记在备忘录里。我来取一箱书，办完这件事，明早就回去。"
    voice "audio/voice/heroine_s01_arrival_l005_v1.ogg"
    h "你还是和以前一样，出门不看天气。"
    "有人从长椅旁站起来。蓝灰色的开衫，右边那枚银色发夹，还有说完话后轻轻抬起的眉。"
    p "许澄？"
    h "嗯。你倒是记得名字。"
    "我本来准备解释这几年为什么没联系，又觉得刚找出来的理由，听上去和三年前一样差。"
    p "……好久不见。"
    h "三年。差两个月。"
    "她没有靠近。我也停在原地，隔着半根柱子的距离，听雨落了一会儿。"
    jump s02_reunion

label s02_reunion:
    $ current_scene = "s02_reunion"
    p "你怎么也来了？"
    h "来取东西。和你一样。"
    "她指了指椅子上的纸袋，袋口夹着一张褪色的照片。照片背后有一道很深的折痕。"
    h "车站清旧库房时找到了它。以前书店借给这里做过一次展览，一直没拿回来。"
    p "这张是那次展览拍的？"
    h "你按了定时快门，又跑回来。照片还是斜了，大半张都是雨棚。"
    p "那时我说，这叫构图。"
    voice "audio/voice/heroine_s02_reunion_l008_v1.ogg"
    h "我知道。你还给照片起了个很长的名字。"
    "她把照片往袋子里按了按。我记起一个阴天：我们坐在这张长椅上，争论这条线什么时候会关。"
    "那时我们觉得，旧地方总会等人回来。后来我走得匆忙，连那张照片都没再看过。"
    h "站务的人说，寄存柜里的东西都搬到出口了。已经替你留好，不用赶。"
    "她说完，把靠近柱子的干燥位置让了出来。袖口却刚好在雨帘边缘。"
    menu:
        "把干燥的位置让给她，问候近况":
            $ affection += 1
            $ trust += 1
            p "你站里面吧。最近过得怎么样？"
            h "还好。书店换了新书架，我少了一项修桌子的工作。"
            "她把袖口往上卷了一点，终于在我旁边坐下。"
            jump s03_letter
        "先确认取物时间，把事情办完":
            $ trust += -1
            p "那我先确认一下，东西今晚能拿走吗？"
            h "能。我刚问过。"
            "她收回纸袋的手停了一下，又把照片整理好。我一时不知道该怎样接下一句。"
            jump s03_letter

label s03_letter:
    $ current_scene = "s03_letter"
    scene expression "cg/unsent_letter.png" with dissolve
    h "还有一样东西，应该也是你的。"
    "她从纸袋里抽出一只没有邮票的信封。边角被压平，纸已经有些发黄。"
    h "夹在展览那本留言册里。那本书上写了你的联系方式，所以他们把它一起送过来了。"
    p "你看过吗？"
    h "没拆。"
    "我认出了自己的字。信封上只有一个“澄”字，最后那一点，落在一道浅浅的水痕里。"
    "离开前一天，我在这里改了很久。写了为什么要走，也写了什么时候想回来。然后，把信藏在了书页之间。"
    "我当时以为，等事情确定下来再交给她会更好。后来总有下一件事，总有一个更合适的明天。"
    h "不知道是谁留下的。名字倒是和我一样。"
    "她把信递过来，手指避开封口。我伸出手，又慢了一瞬。"
    voice "audio/voice/heroine_s03_letter_l011_v1.ogg"
    h "你不用现在打开。"
    "纸很轻。我却发现，拿着它的时候，刚才准备好的那些寒暄都不太够用了。"
    menu:
        "告诉她：这封信是我写的":
            $ trust += 1
            $ truth_known = True
            p "是我写给你的。出发前一天。"
            h "……那为什么没给我？"
            p "我怕答应了做不到，也怕你说不用等。所以把这个决定，一起拖下去了。"
            h "你至少可以告诉我，你还没决定。"
            p "嗯。那是我应该做的。"
            "她没有马上笑。我把信封放在膝上，第一次让这件事有了一个明确的答案。"
            jump s04_waiting
        "先收好信，暂时不解释":
            $ trust += -1
            p "可能是以前遗漏的东西。我先收起来。"
            h "嗯。"
            "她把手缩回开衫的袖口，没有追问。我把信放进口袋，边角蹭过掌心。"
            jump s04_waiting

label s04_waiting:
    $ current_scene = "s04_waiting"
    scene expression "backgrounds/station_rain.png" with dissolve
    show heroine normal at heroine_position with dissolve
    "站台尽头的灯灭了一盏。我们一起往靠近出口的长椅挪，重新坐到灯下。"
    h "你明天还要走？"
    p "嗯。请的假不长。"
    h "我不是问你能留多久。"
    "她看了看我口袋露出的信封。我把手机放在椅面上，没有再打开叫车页面。"
    p "我知道。"
    h "以前你说要走的时候，我正想着把照片洗出来。还有一张拍得比较端正，没来得及给你。"
    p "你一直留着？"
    h "那是我自己也在里面的一张照片。当然要留。"
    "她说得很平常。我却忽然松了一口气：她有自己的生活，也有自己保存东西的理由。"
    h "我后来换了工作，也搬了家。这几年，不是在这里等一班早就开走的车。"
    p "我也不想你那样等。"
    voice "audio/voice/heroine_s04_waiting_l013_v1.ogg"
    h "我知道。但有些话，如果只放在心里，别人听不见。"
    "雨声从急促变得均匀。一阵风把告示的一角掀起来，露出下面旧时刻表的一小段。"
    p "你说得对。"
    h "如果你明天就要走，今天就说今天能做到的事。比如，回去以后给我发个消息。"
    p "这个能做到。"
    h "那就记着。别再拿手机没电当理由。"
    "我拿出手机，给她发了一个句号。她的屏幕亮起来，头像还是当年那只画得有点歪的猫。"
    h "句号不算消息。"
    p "至少能证明号码没错。"
    "她很轻地笑了一声，又把手机收好。这一次，我没有急着替这声笑解释什么。"
    jump s05_departure

label s05_departure:
    $ current_scene = "s05_departure"
    "雨小了一些。出口的保安敲了敲玻璃，示意我们该收东西了。"
    "我拎起纸箱，里面的书在搬动时发出沉沉的一声。许澄把照片装进纸袋，撑开伞。"
    h "外面那家小店还开着。雨太大时，我会进去坐一会儿。"
    p "还是卖热牛奶的那家？"
    h "已经换了老板。不过热水还是免费的。"
    "伞面轻轻碰到栏杆。她停下来，看着我，像是在等一个不需要猜的答复。"
    voice "audio/voice/heroine_s05_departure_l007_v1.ogg"
    h "要一起走到那边吗？"
    "明早的车票还在手机里。眼前这段路，却只有今晚。"
    menu:
        "和她一起走，继续聊一会儿":
            $ affection += 1
            p "好。纸箱我提着，伞可以借我拿吗？"
            h "你拿左边。我不想再湿一次袖口。"
            "她把伞柄挪到两个人之间。我接过去，跟上她的步子。"
            jump s06_resolution
        "今晚先各自回家，改天再联系":
            $ trust += -1
            p "今晚先回去吧。到家以后，我会给你发消息。"
            h "好。我听见了。"
            "她点了点头，把伞撑正。我们把“下次”留了下来，也把今晚各自的路说清楚。"
            jump s06_resolution

label s06_resolution:
    $ current_scene = "s06_resolution"
    if affection >= 2 and trust >= 1 and truth_known == True:
        jump s07_true
    else:
        jump s08_normal

label s07_true:
    $ current_scene = "s07_true"
    scene black with dissolve
    "车站外的路比记忆里短。伞沿滴下的水落在鞋边，纸箱有一半，一直留在干燥的地方。"
    h "你把伞全偏过来了。"
    p "我这边已经湿过，不差这一点。"
    h "那也不用重新湿一遍。"
    "她抓住伞柄，往我这边推了推。我们都慢下来，终于把步子走到差不多的长度。"
    "小店的灯还亮着。桌上有水杯、纸巾，和一碟并不特别好吃的饼干。我们坐下，没有谁急着给今晚取名字。"
    p "等我把箱子放好，能把那封信重新写一遍吗？"
    h "旧的也留着。写过的话，不能因为不好意思就当作没发生。"
    p "那我把现在的放在后面。"
    h "嗯。这次记得交给我。"
    "她从纸袋里抽出那张照片，放到桌子中间。拍得确实有些歪。雨棚、长椅，还有并肩站着的两个人，都在里面。"
    "我把明早的车次告诉她。她说了明天几点上班，又问我到了以后，什么时候方便说话。"
    "我们的生活没有突然变得容易。只是下一次联系的时间，终于从一个含糊的词，变成了双方都知道的约定。"
    voice "audio/voice/heroine_s07_true_l014_v1.ogg"
    h "到家以后，发一条有内容的消息。"
    p "好。第一条就告诉你，这次伞没有忘。"
    "窗外，最后几滴雨从招牌上滑下来。桌上的旧信被水杯压住一角，稳稳地留在灯下。"
    $ last_ending = "true"
    stop music fadeout 2.0
    stop ambient fadeout 2.0
    call screen ending_card("True / 把今天说清楚")
    return

label s08_normal:
    $ current_scene = "s08_normal"
    scene expression "backgrounds/station_rain.png" with dissolve
    "十分钟后，我站在车站外，看着最后几滴雨落进路边的积水。旧箱子靠着腿，信封还放在口袋里。"
    "刚才的话，有些说了，有些没有说。有些本来只要一句，到了嘴边，却被我换成另一句。"
    "许澄没有替我把这些空白填好。我也没有权利把她的沉默，理解成一切都已经过去。"
    "手机亮起来。她发来一张旧照片，下面只有一行字。"
    h "这张没有拍歪。你回去以后，慢慢看。"
    p "谢谢。到家我给你发消息。"
    "我输入了完整的一句话，没有用句号代替。发送以后，又把信封按平了一点。"
    "车站关闭的时间已经写在告示上。另一些事情，今晚还没有确定。"
    "我可以继续把它们留给以后，也可以在下一次联系时，先把该说的话说出来。"
    "雨停了。这个晚上没有给出所有答案，但我们已经重新有了彼此的号码。"
    $ last_ending = "normal"
    stop music fadeout 2.0
    stop ambient fadeout 2.0
    call screen ending_card("Normal / 留给下一次的话")
    return

