# Generated by python -m tools.compile_story; edit game/data/story.json.
# Story SHA-256: 2c4f18f368f18122e76b0d42729aa3c57c9642a4d78f0d4841a9d9a56f5353b9

label start:
    $ affection = 0
    $ trust = 0
    $ truth_known = False
    $ last_ending = ""
    jump bootstrap_arrival

label bootstrap_arrival:
    $ current_scene = "bootstrap_arrival"
    scene expression "backgrounds/station_placeholder.png" with dissolve
    show heroine normal at heroine_position with dissolve
    play music "audio/bgm/rain_theme.ogg" fadein 1.0
    play ambient "audio/sfx/rain_ambience.ogg" fadein 1.0
    "雨从旧车站的檐边落下来。我看了一眼停运告示，把手机收进口袋。"
    "站台另一头有人抬起了伞。"
    h "你也是来等最后一班车的吗？"
    p "看起来，我们都来晚了。"
    jump bootstrap_choice

label bootstrap_choice:
    $ current_scene = "bootstrap_choice"
    h "出口还有一段露天的路。要一起走吗？"
    menu:
        "和她共撑一把伞":
            $ affection += 1
            $ trust += 1
            $ truth_known = True
            jump bootstrap_true
        "留下来等雨停":
            $ trust += -1
            jump bootstrap_normal

label bootstrap_true:
    $ current_scene = "bootstrap_true"
    p "谢谢。我来拿伞吧。"
    h "好。路上，正好有件事想问你。"
    "我们并肩走下站台。湿漉漉的路灯，在两个人的脚边亮了起来。"
    $ last_ending = "true"
    stop music fadeout 2.0
    stop ambient fadeout 2.0
    call screen ending_card("工程样片 · 一起走")
    return

label bootstrap_normal:
    $ current_scene = "bootstrap_normal"
    p "我再等等。你先走吧。"
    h "嗯。希望这场雨不会太久。"
    "她的脚步声消失在雨里。我打开了手机，重新寻找回家的路。"
    $ last_ending = "normal"
    stop music fadeout 2.0
    stop ambient fadeout 2.0
    call screen ending_card("工程样片 · 等雨停")
    return

