# Generated by python -m tools.compile_story; edit game/data/story.json.
# Story SHA-256: 867d687f21a109a92075316796ce4cf59f037568362f836da36c19143a23773b

label start:
    $ affection = 0
    $ trust = 0
    $ truth_known = False
    $ last_ending = ""
    $ current_chapter = ""
    $ visited_scenes = []
    jump p00_entry

label p00_entry:
    $ current_scene = "p00_entry"
    $ current_chapter = "ch00"
    $ visited_scenes.append("p00_entry")
    scene black with dissolve
    centered "序章 ： 雨夜"
    scene expression "backgrounds/station_rain.png" with dissolve
    play music "audio/bgm/rain_theme.ogg" fadein 1.0
    play ambient "audio/sfx/rain_ambience.ogg" fadein 1.0
    "清库通知是下午收到的：旧站最后一天开放，未领取的寄存物会统一移交。我从外地回来，把今晚留给这一箱书。"
    "订票时我算过时间。取东西，找住处，明早离开，安排得很满，几乎没给临时的事留位置。"
    "出租车停在路口。雨棚的灯还亮着，售票窗里却已经空了，只剩一块写着停运的牌子。"
    "通知末尾说，值班的人会把箱子放在出口。我把柜号重新核对一遍，才发现备忘录仍用着三年前的标题。"
    p "书应该还在吧。"
    "我想起夹在展览留言册里的那封信。那时写完没有送出去，后来也没有回来找过。"
    "如果这次找不到，就算了。这句话刚冒出来，我便把手机按灭：今天至少要把该拿的东西拿走。"
    "雨水从檐角落到鞋上。我没有带伞，只能拎着空布袋，往檐下那条窄窄的干地走。"
    jump s01_arrival

label s01_arrival:
    $ current_scene = "s01_arrival"
    $ current_chapter = "ch00"
    $ visited_scenes.append("s01_arrival")
    play music "audio/bgm/rain_theme.ogg" fadein 1.0
    play ambient "audio/sfx/rain_ambience.ogg" fadein 1.0
    "雨从车站的铁皮檐边落下来，连成一层薄薄的帘。路灯照着停运告示，也照着我已经湿透的鞋尖。"
    "手机上的网约车排队数从十二变成十三。我把它收进口袋，沿着熟悉的柱子往里走。"
    "三年前，这个时候的站台会很吵。今天，只有雨点撞在轨道上的声音。"
    "旧寄存柜的号码还记在备忘录里。我来取一箱书，办完这件事，明早就回去。"
    show heroine smile at heroine_position
    voice "audio/voice/heroine_s01_arrival_l005_v1.ogg"
    h "你还是和以前一样，出门不看天气。"
    "有人从长椅旁站起来。蓝灰色的开衫，右边那枚银色发夹，还有说完话后轻轻抬起的眉。"
    p "许澄？"
    show heroine smile at heroine_position
    h "嗯。你倒是记得名字。"
    "我本来准备解释这几年为什么没联系，又觉得刚找出来的理由，听上去和三年前一样差。"
    p "……好久不见。"
    show heroine normal at heroine_position
    h "三年。差两个月。"
    "她没有靠近。我也停在原地，隔着半根柱子的距离，听雨落了一会儿。"
    jump s01_platform

label s01_platform:
    $ current_scene = "s01_platform"
    $ current_chapter = "ch00"
    $ visited_scenes.append("s01_platform")
    "她的纸袋贴着椅背，底下垫了一张报纸。雨飘进来时，她先扶住袋口，才看我一眼。"
    p "里面没湿吧？"
    show heroine normal at heroine_position
    h "底下是干的。比你那只袋子可靠。"
    "我低头看了看手里的布袋，边角正往下滴水。为了少淋两步，我刚才把它顶在了头上。"
    p "本来是拿来装书的。"
    show heroine smile at heroine_position
    h "那等会儿别把书放进去。"
    "我拧了一下袋角，把水滴到雨棚外。她往旁边让出一点，替我避开那块松动的地砖。"
    "以前走到这里，我不必抬头也知道她会往哪边站。这次我等她站稳，才跨过地砖。"
    p "谢谢。"
    "她点了点头。出口那边有推车经过，轮子在接缝上响了两声。我终于找到了一个能开口的问题。"
    jump s02_reunion

label s02_reunion:
    $ current_scene = "s02_reunion"
    $ current_chapter = "ch01"
    $ visited_scenes.append("s02_reunion")
    scene black with dissolve
    centered "第一章 ： 重逢"
    scene expression "backgrounds/station_rain.png" with dissolve
    show heroine normal at heroine_position with dissolve
    p "你怎么也来了？"
    h "来取东西。和你一样。"
    "她指了指椅子上的纸袋，袋口夹着一张褪色的照片。照片背后有一道很深的折痕。"
    h "车站清旧库房时找到了它。以前书店借给这里做过一次展览，一直没拿回来。"
    p "这张是那次展览拍的？"
    show heroine embarrassed at heroine_position
    h "你按了定时快门，又跑回来。照片还是斜了，大半张都是雨棚。"
    p "那时我说，这叫构图。"
    show heroine smile at heroine_position
    voice "audio/voice/heroine_s02_reunion_l008_v1.ogg"
    h "我知道。你还给照片起了个很长的名字。"
    "她把照片往袋子里按了按。我记起一个阴天：我们坐在这张长椅上，争论这条线什么时候会关。"
    "那时我们觉得，旧地方总会等人回来。后来我走得匆忙，连那张照片都没再看过。"
    show heroine normal at heroine_position
    h "站务的人说，寄存柜里的东西都搬到出口了。已经替你留好，不用赶。"
    "她说完，把靠近柱子的干燥位置让了出来。袖口却刚好在雨帘边缘。"
    menu:
        "把干燥的位置让给她，问候近况":
            $ affection += 1
            $ trust += 1
            p "你站里面吧。最近过得怎么样？"
            show heroine smile at heroine_position
            h "还好。书店换了新书架，我少了一项修桌子的工作。"
            "她把袖口往上卷了一点，挪到我身边干燥的位置。"
            jump s02_care
        "先确认取物时间，把事情办完":
            $ trust += -1
            p "那我先确认一下，东西今晚能拿走吗？"
            show heroine normal at heroine_position
            h "能。我刚问过。"
            "她收回纸袋的手停了一下，又把照片整理好。我一时不知道该怎样接下一句。"
            jump s02_business

label s02_care:
    $ current_scene = "s02_care"
    $ current_chapter = "ch01"
    $ visited_scenes.append("s02_care")
    p "还在原来那条街吗？"
    show heroine normal at heroine_position
    h "搬到街口了。小一点，窗户倒比以前大。"
    p "那张总晃的桌子也搬了？"
    show heroine happy at heroine_position
    h "没搬。老板终于同意，它不适合当收银台。"
    "我记得桌脚塞着一本旧杂志。有一回零钱掉进缝里，我们拆了半天抽屉，也没想过换张桌子。"
    p "听起来现在省心一些。"
    show heroine smile at heroine_position
    h "也没有。新架子很高，最上层的书每天都有人要。只是麻烦换了一种。"
    "她说到这里，拿手机给我看店里新拍的照片。窗边放着一盆薄荷，叶子在白色桌面上投了很小的影子。"
    p "这张拍得很正。"
    show heroine smile at heroine_position
    h "练了三年。不能一直怪相机。"
    "我没有把手机里的书店当作一条让我放心的证据。我只是记住了地址，问她哪天不用值晚班。"
    jump s02_boxes

label s02_business:
    $ current_scene = "s02_business"
    $ current_chapter = "ch01"
    $ visited_scenes.append("s02_business")
    p "出口那边还要登记吗？"
    show heroine normal at heroine_position
    h "签一下名字就行。箱子上写了柜号。"
    "我把通知翻出来，指尖在柜号上停了一下。许澄看完，把纸袋往自己那边挪回去。"
    p "你也要签？"
    h "我已经签好了。怕下雨，就在这里整理。"
    "接下来似乎只剩过去拿箱子。我看了一眼出口，又看了一眼她的袖口，不知道先说哪一件合适。"
    p "你这边还没弄完？"
    show heroine sad at heroine_position
    h "照片背面有几个日期，要分清。你要赶时间，可以先办你的。"
    p "没有那么急。我帮你照一下？这里有点暗。"
    "她没有把纸袋递给我，只指了指靠柱子的地方。我打开手机电筒，照着袋口，让她自己把东西排好。"
    "能帮上的事很小。我把光往下压了压，没有趁她看日期时继续问私人问题。"
    jump s02_boxes

label s02_boxes:
    $ current_scene = "s02_boxes"
    $ current_chapter = "ch01"
    $ visited_scenes.append("s02_boxes")
    "出口的推车停住了。我的柜号贴在最上面的纸箱上，胶带已经换过，底部干干净净。"
    "我过去签了字，把箱子搬到长椅旁。工作人员留下了一截新胶带，关门前还可以重新封好。"
    p "比记得的重。"
    show heroine normal at heroine_position
    h "你当时说只有几本。"
    "我掀开箱盖。展览用的书、空相框，还有那本厚留言册，都按大小放着。最上面夹了一张移交清单。"
    p "原来都留着。"
    h "照片是书店借出去的。我来拿走，下次做展览还能用。"
    "她在清单上找到书店的名字，把相框挑了出来。我把其余的书重新码平，给她的纸袋留出空间。"
    p "这些字还看得清。"
    "留言册封皮上是我当年的号码。我没急着翻页，许澄却把手伸进纸袋，摸到了一件刚才没摆出来的东西。"
    jump s03_letter

label s03_letter:
    $ current_scene = "s03_letter"
    $ current_chapter = "ch02"
    $ visited_scenes.append("s03_letter")
    scene black with dissolve
    centered "第二章 ： 旧信"
    scene expression "cg/unsent_letter.png" with dissolve
    h "还有一样东西，应该也是你的。"
    "她从纸袋里抽出一只没有邮票的信封。边角被压平，纸已经有些发黄。"
    h "夹在展览那本留言册里。那本书上写了你的联系方式，所以他们把它一起送过来了。"
    p "你看过吗？"
    h "没拆。"
    "我认出了自己的字。信封上只有一个“澄”字，最后那一点，落在一道浅浅的水痕里。"
    "离开前一天，我在这里改了很久。写了为什么要走，也写了什么时候想回来。然后，把信藏在了书页之间。"
    "我当时以为，等事情确定下来再交给她会更好。后来总有下一件事，总有一个更合适的明天。"
    h "不知道是谁留下的。名字倒是和我一样。"
    "她把信递过来，手指避开封口。我伸出手，又慢了一瞬。"
    voice "audio/voice/heroine_s03_letter_l011_v1.ogg"
    h "你不用现在打开。"
    "纸很轻。我却发现，拿着它的时候，刚才准备好的那些寒暄都不太够用了。"
    menu:
        "告诉她：这封信是我写的":
            $ trust += 1
            $ truth_known = True
            p "是我写给你的。出发前一天。"
            h "……那为什么没给我？"
            p "我怕答应了做不到，也怕你说不用等。所以把这个决定，一起拖下去了。"
            h "你至少可以告诉我，你还没决定。"
            p "嗯。那是我应该做的。"
            "她没有马上笑。我把信封平放在纸箱上，第一次让这件事有了一个明确的答案。"
            jump s03_honest
        "先收好信，暂时不解释":
            $ trust += -1
            p "可能是以前遗漏的东西。我先收起来。"
            h "嗯。"
            "她把手缩回开衫的袖口，没有追问。我把信放进口袋，边角蹭过掌心。"
            jump s03_deferred

label s03_honest:
    $ current_scene = "s03_honest"
    $ current_chapter = "ch02"
    $ visited_scenes.append("s03_honest")
    p "里面写的是那时候的打算。有些后来没有做到。"
    h "那就别让我拿三年前的打算，猜你现在要说什么。"
    "信封压在箱盖上，封口仍旧平整。我伸出的手又收了回来，没有用拆信代替回答。"
    p "我会重新说。你也不用今天就给我答复。"
    h "我还不知道你写了什么。要不要看，也得让我自己决定。"
    p "好。我先把信收好，等我们都愿意谈的时候再拿出来。"
    "她把纸袋拉近一些，给我让出整理箱子的地方。刚才那一点停顿还在，我没有把它当作拒绝。"
    h "还有，别把所有没做到的事都算成一件。有的已经过去了，有的现在还能说明白。"
    "我看着箱子里的书，慢慢点了点头。今晚能先做的一件，是不再替她决定什么时候听。"
    jump s03_archive

label s03_deferred:
    $ current_scene = "s03_deferred"
    $ current_chapter = "ch02"
    $ visited_scenes.append("s03_deferred")
    "信封沉到口袋底部。我用手掌隔着布料压了一下，怕边角折起来，也怕自己又把它拿出来。"
    h "你认识那上面的字吗？"
    p "认识。只是现在还没想好怎么说。"
    "我终于停在这句话上，没有再说“可能”，也没有找一个关于年代太久的理由。"
    h "那就先不说。"
    p "你不会觉得很奇怪吗？"
    h "会。但我可以等你说，不用替你猜一个答案。"
    "她把纸袋里的照片叠齐，仍然把封口朝上留着。我们之间多出一段空白，谁也没有假装它已经填好了。"
    p "至少，这次我记得它在哪。"
    "这句话听上去还算诚实，却不足以让她知道更多。我把手从口袋里拿出来，继续整理眼前的箱子。"
    jump s03_archive

label s03_archive:
    $ current_scene = "s03_archive"
    $ current_chapter = "ch02"
    $ visited_scenes.append("s03_archive")
    scene expression "backgrounds/station_rain.png" with dissolve
    show heroine normal at heroine_position with dissolve
    "我把信放进口袋里干燥的那一侧，又把留言册装回箱子。胶带没有贴死，搬走前还能再看一眼。"
    show heroine normal at heroine_position
    h "这本书你带走吧。书店不用了。"
    p "照片都找齐了吗？"
    h "齐了。相框没必要全拿，有两个边角已经坏了。"
    "她抽出一张旧清单，在不要的相框旁做了记号。保留什么、丢掉什么，她都分得很清楚。"
    p "我好像每一件都觉得还能用。"
    show heroine smile at heroine_position
    h "那就先带回去。不过你的布袋现在只能装空相框。"
    "我摸了摸袋子的外层，果然还是湿的。最后还是把书留在纸箱里，空袋挂在手腕上。"
    "整理完以后，椅面空出了一大块。雨棚外没有车经过，广播也不再报站，我们终于不用和别的声音抢着说话。"
    jump s04_gate

label s04_gate:
    $ current_scene = "s04_gate"
    $ current_chapter = "ch03"
    $ visited_scenes.append("s04_gate")
    scene black with dissolve
    centered "第三章 ： 空白"
    scene expression "backgrounds/station_rain.png" with dissolve
    show heroine normal at heroine_position with dissolve
    if trust >= 1:
        jump s04_open
    else:
        jump s04_reserved

label s04_open:
    $ current_scene = "s04_open"
    $ current_chapter = "ch03"
    $ visited_scenes.append("s04_open")
    show heroine normal at heroine_position
    h "你这次回来，原本只安排了取东西？"
    p "嗯。明早的车票也买好了。"
    h "那现在还有一点时间。你想怎么用？"
    "我看了眼手机，没有未接来电。先前排得满满的晚上，取完箱子以后，忽然空出了一小段。"
    p "想跟你说说话。如果你不急着走。"
    show heroine smile at heroine_position
    h "我不急。不过也不是为了让你把三年一次说完。"
    p "我可能还是会说得很慢。"
    h "慢一点可以。你说到哪，我就听到哪。"
    "她把手机放进纸袋的侧袋，留出一只手整理袖口。我把箱盖盖好，决定让今晚剩下的时间慢一点过。"
    jump s04_waiting

label s04_reserved:
    $ current_scene = "s04_reserved"
    $ current_chapter = "ch03"
    $ visited_scenes.append("s04_reserved")
    "椅面已经收拾干净，许澄却没有继续往我这边挪。她看了看出口，把纸袋提起来又放下。"
    p "你要走了吗？"
    show heroine normal at heroine_position
    h "一会儿。我想先确认，你是要聊，还是只想安静等雨小一点。"
    p "两个都想。只是有些话，我一时找不到开头。"
    h "可以。但你没说的部分，我不会当作已经知道。"
    "我刚才几次开口，都只讲了事情的边缘。让她从这些边缘拼出答案，确实不公平。"
    p "那我先不让你猜。"
    show heroine sad at heroine_position
    h "也不用为了填空，随便答应什么。今天能说哪一件，就说哪一件。"
    "这不是她替我把话接下去。她只是留出了一个位置，要不要走进去，还得由我自己决定。"
    jump s04_waiting

label s04_waiting:
    $ current_scene = "s04_waiting"
    $ current_chapter = "ch03"
    $ visited_scenes.append("s04_waiting")
    scene expression "backgrounds/station_rain.png" with dissolve
    show heroine normal at heroine_position with dissolve
    "站台尽头的灯灭了一盏。我们一起往靠近出口的长椅挪，在灯下停了下来。"
    show heroine sad at heroine_position
    h "你明天还要走？"
    p "嗯。请的假不长。"
    show heroine angry at heroine_position
    h "我不是问你能留多久。"
    "她看了看我口袋露出的信封。我把手机放在椅面上，没有再打开叫车页面。"
    p "我知道你要问的是什么。"
    show heroine sad at heroine_position
    h "以前你说要走的时候，我正想着把照片洗出来。还有一张拍得比较端正，没来得及给你。"
    p "你一直留着？"
    show heroine embarrassed at heroine_position
    h "那是我自己也在里面的一张照片。当然要留。"
    "她说得很平常。我却忽然松了一口气：她有自己的生活，也有自己保存东西的理由。"
    show heroine normal at heroine_position
    h "我后来换了工作，也搬了家。这几年，不是在这里等一班早就开走的车。"
    p "我也不想你那样等。"
    voice "audio/voice/heroine_s04_waiting_l013_v1.ogg"
    h "我知道。但有些话，如果只放在心里，别人听不见。"
    "雨声从急促变得均匀。一阵风把告示的一角掀起来，露出下面旧时刻表的一小段。"
    p "你说得对。"
    h "如果你明天就要走，今天就说今天能做到的事。比如，回去以后给我发个消息。"
    p "这个能做到。"
    show heroine smile at heroine_position
    h "那就记着。别再拿手机没电当理由。"
    "我拿出手机，给她发了一个句号。她的屏幕亮起来，头像还是当年那只画得有点歪的猫。"
    show heroine surprised at heroine_position
    h "句号不算消息。"
    p "至少能证明号码没错。"
    show heroine happy at heroine_position
    "她很轻地笑了一声，又把手机收好。这一次，我没有急着替这声笑解释什么。"
    jump s04_memory

label s04_memory:
    $ current_scene = "s04_memory"
    $ current_chapter = "ch04"
    $ visited_scenes.append("s04_memory")
    scene black with dissolve
    centered "第四章 ： 今天"
    scene expression "backgrounds/station_rain.png" with dissolve
    show heroine normal at heroine_position with dissolve
    p "另一张照片，是什么时候拍的？"
    show heroine smile at heroine_position
    h "收展那天。你说这次一定拍正，又把相机垫在了报纸上。"
    "我想起来了。报纸被风掀起一角，定时快门已经响起来，我伸手按它，差点没站进画面。"
    p "结果正了吗？"
    h "正了。你倒是只剩半边肩膀。"
    "她把那张照片从袋子里抽出一点，只给我看了边缘。我的外套在画面最左侧，袖口有一团模糊的雨水。"
    p "我都不记得还有这张。"
    show heroine normal at heroine_position
    h "你可以不记得。我留着，是因为那天的展览很好，不想连同车站一起忘掉。"
    "照片属于她，也属于那个下午。我曾经急着从旧物里找一句原谅，这时才认真看了看它拍下的地方。"
    p "那天你摆了好久的书。"
    show heroine smile at heroine_position
    h "下次摆展的时候，我可不想再拿报纸垫相机。"
    "她把照片收回去。我没有伸手要，想着以后可以给她现在工作的书店也拍一张。"
    jump s04_boundary

label s04_boundary:
    $ current_scene = "s04_boundary"
    $ current_chapter = "ch04"
    $ visited_scenes.append("s04_boundary")
    p "我有时候分不清，什么现在说还来得及，什么说了只会添麻烦。"
    show heroine normal at heroine_position
    h "你可以先问我愿不愿意听。"
    p "问完以后呢？"
    h "听了不一定能马上回答。这个也得允许。"
    "我以前总把她的回答预先写好。有时是拒绝，有时是原谅，最后连真正的问题都没问。"
    p "我以为不说就不会让你为难。"
    show heroine angry at heroine_position
    h "不说，也不能替我决定我会不会为难。"
    "她把话停在那里，没有提高声音。我伸手扶住箱盖，没拿“为你好”把自己的犹豫遮过去。"
    p "那今晚可以再听一点吗？不是要你马上答应什么。"
    show heroine normal at heroine_position
    h "可以。只说你自己能确定的部分。"
    "雨棚下一滴水落在胶带上。我用袖口擦掉，想了想三年前写下的话，也想了想明天回去以后能做的事。"
    jump s04_revisit

label s04_revisit:
    $ current_scene = "s04_revisit"
    $ current_chapter = "ch04"
    $ visited_scenes.append("s04_revisit")
    "手机的屏幕又亮起来，是明早的乘车提醒。我把到站时间看了一遍，没有将提醒划掉。"
    p "明天还是得走。"
    show heroine normal at heroine_position
    h "嗯。车票不用因为今晚变掉。"
    "口袋里的信封没有动。写信那天，我把每一句话都写成以后：以后回来，以后带她去看另一次展览。"
    "现在能确定的事情很少。我明早上车，下午到家；她明天去书店，休息时才方便看消息。"
    p "你通常几点能歇一会儿？"
    h "四点左右。不一定每天准时。"
    "我把这个时间记下，没有设成每天响的闹钟。约定可以改，但改动也应该让对方知道。"
    "还剩两种说法。一种从那封信开始，把当时没交出去的话带回现在；另一种先约好下一次，不急着处理所有旧事。"
    "她看着我，留了几秒。我这次没有用一个句号占住空白。"
    menu:
        "把信里的意思和今天的打算说清楚":
            $ affection += 1
            $ trust += 2
            $ truth_known = True
            jump s04_repair
        "先约定下一次联系，旧事慢慢谈":
            $ trust += 1
            jump s04_concrete

label s04_repair:
    $ current_scene = "s04_repair"
    $ current_chapter = "ch04"
    $ visited_scenes.append("s04_repair")
    p "那封信，是我出发前写给你的。里面说我想再回来，也想跟你继续见面。"
    "这一次，句子没有停在“以后”。我看着她，把信里属于自己的那一部分重新说了一遍。"
    p "现在也一样。但你不需要替我保证这件事会变成什么。"
    show heroine normal at heroine_position
    h "你想继续见面，和你能够什么时候回来，是两件事。"
    p "我知道。下一次假期还没定，我不会先给一个日期。明天到家以后，我会告诉你。"
    h "如果计划变了呢？"
    p "说计划变了。不是等到都安排好了，才敢联系。"
    "她看了我一会儿，伸手把纸袋卷好的袋口压平。刚才没说完的话，终于不需要她去猜作者。"
    show heroine embarrassed at heroine_position
    h "那我也说清楚。见面我愿意，什么时候有空，我会自己告诉你。"
    p "好。还有那封旧信，要看之前，我会再问你。"
    show heroine smile at heroine_position
    h "你把现在的写在后面吧。别拿旧日期当借口。"
    "我把到家时间发过去，后面补上“你有空再回”。消息停在屏幕上，这次比一个句号长得多。"
    jump s05_departure

label s04_concrete:
    $ current_scene = "s04_concrete"
    $ current_chapter = "ch04"
    $ visited_scenes.append("s04_concrete")
    p "旧事慢一点说。明天下午我到了，先给你发消息，可以吗？"
    show heroine normal at heroine_position
    h "可以。我四点不一定看得到，忙完了会回。"
    p "不用按点。你忙的时候，我也不会一直问。"
    "我打开刚才的聊天，把预计到家的时间写上。写完又检查了一遍，删掉“肯定”，改成车次正常时的大概时间。"
    h "这样就够了。你晚一点也可以说，不必等到晚上才解释。"
    p "如果我又不知道该说什么呢？"
    show heroine smile at heroine_position
    h "从今天读了什么开始。书店新到了几本，我还没看完。"
    "我把箱子上那本书翻给她看，封面边缘已经卷了。她报出书名，问里面是不是还夹着那张旧车票。"
    p "回去找找。有的话，拍给你看。"
    show heroine normal at heroine_position
    h "没有也能说没有。"
    "关于口袋里的信，我们没再往下谈。我没有把这一点具体的约定当作所有问题都已经解决，只把她的消息置顶了一晚。"
    jump s05_departure

label s05_departure:
    $ current_scene = "s05_departure"
    $ current_chapter = "ch05"
    $ visited_scenes.append("s05_departure")
    scene black with dissolve
    centered "第五章 ： 雨停之前"
    scene expression "backgrounds/station_rain.png" with dissolve
    show heroine normal at heroine_position with dissolve
    "雨小了一些。出口的保安敲了敲玻璃，示意我们该收东西了。"
    "我拎起纸箱，里面的书在搬动时发出沉沉的一声。许澄把照片装进纸袋，撑开伞。"
    show heroine smile at heroine_position
    h "外面那家小店还开着。雨太大时，我会进去坐一会儿。"
    p "还是卖热牛奶的那家？"
    h "已经换了老板。不过热水还是免费的。"
    "伞面轻轻碰到栏杆。她停下来，看着我，像是在等一个不需要猜的答复。"
    show heroine embarrassed at heroine_position
    voice "audio/voice/heroine_s05_departure_l007_v1.ogg"
    h "要一起走到那边吗？"
    "明早的车票还在手机里。眼前这段路，却只有今晚。"
    menu:
        "和她一起走，继续聊一会儿":
            $ affection += 1
            p "好。纸箱我提着，伞可以借我拿吗？"
            show heroine smile at heroine_position
            h "你拿左边。我不想再湿一次袖口。"
            "她把伞柄挪到两个人之间。我接过去，跟上她的步子。"
            jump s05_shared_path
        "今晚先各自回家，改天再联系":
            $ trust += -1
            p "今晚先回去吧。到家以后，我会给你发消息。"
            show heroine normal at heroine_position
            h "好。我听见了。"
            "她点了点头，把伞撑正。我们把“下次”留了下来，也把今晚各自的路说清楚。"
            jump s05_separate_path

label s05_shared_path:
    $ current_scene = "s05_shared_path"
    $ current_chapter = "ch05"
    $ visited_scenes.append("s05_shared_path")
    "纸箱底角擦过椅背，响了一声。我检查胶带有没有贴牢，握稳左手的伞，许澄绕过那块松动的地砖。"
    show heroine normal at heroine_position
    h "别照着以前走。门口那级台阶拆了。"
    p "难怪看着少了点什么。"
    "走到出口，雨棚忽然窄了一截。她把纸袋换到里面那只手，我停下来，等她调整好再往前。"
    p "这样拿得住吗？"
    h "拿得住。你箱子别碰栏杆就好。"
    "我的脚步还是比她快半步。我往回收了一点，让箱子在两个人身前留出同样的距离。"
    "小店的灯就在街角，门口也有一段能避雨的檐。走过去不远，但走到那里以后，我们仍可以各自决定要不要再留一会儿。"
    jump s06_resolution

label s05_separate_path:
    $ current_scene = "s05_separate_path"
    $ current_chapter = "ch05"
    $ visited_scenes.append("s05_separate_path")
    "我把箱盖的胶带压牢，打开叫车页面。排队数已经清零，车会停在出口旁边，牌号最后两位是七六。"
    p "车快到了。你不用陪我等。"
    show heroine normal at heroine_position
    h "好。我往街角走，那边有路灯。"
    "我们把纸箱和纸袋分别提起来。许澄撑开自己的伞，先跨过出口外那道积水。"
    p "明天下午我发消息。"
    h "看到了会回。今天先各自平安到家。"
    "她往小店的方向走，我留在出口的檐下。叫车页面上的预计时间又延长了几分钟，我把箱子放下，让它靠住腿。"
    "信还在口袋里。没有因为这次道别消失，也没有替我改变刚才说出的决定。车灯还没拐进路口，我又看了一眼雨棚。"
    jump s08_normal

label s06_resolution:
    $ current_scene = "s06_resolution"
    $ current_chapter = "ch05"
    $ visited_scenes.append("s06_resolution")
    if affection >= 2 and trust >= 2 and truth_known == True:
        jump s07_true
    else:
        jump s08_normal

label s07_true:
    $ current_scene = "s07_true"
    $ current_chapter = "ch05"
    $ visited_scenes.append("s07_true")
    scene black with dissolve
    "车站外的路比记忆里短。伞沿滴下的水落在鞋边，纸箱有一半，一直留在干燥的地方。"
    h "你把伞全偏过来了。"
    p "我这边已经湿过，不差这一点。"
    h "那也不用重新湿一遍。"
    "她抓住伞柄，往我这边推了推。我们都慢下来，终于把步子走到差不多的长度。"
    "小店的灯还亮着。桌上有水杯、纸巾，和一碟并不特别好吃的饼干。我们坐下，没有谁急着给今晚取名字。"
    p "等我把箱子放好，能把那封信重新写一遍吗？"
    h "旧的也留着。写过的话，不能因为不好意思就当作没发生。"
    p "那我把现在的放在后面。"
    h "嗯。这次记得交给我。"
    "她从纸袋里抽出那张照片，放到桌子中间。拍得确实有些歪。雨棚、长椅，还有并肩站着的两个人，都在里面。"
    "我把明早的车次告诉她。她说了明天几点上班，又问我到了以后，什么时候方便说话。"
    "我们的生活没有突然变得容易。只是下一次联系的时间，终于从一个含糊的词，变成了双方都知道的约定。"
    voice "audio/voice/heroine_s07_true_l014_v1.ogg"
    h "到家以后，发一条有内容的消息。"
    p "好。第一条就告诉你，这次伞没有忘。"
    "窗外，最后几滴雨从招牌上滑下来。桌上的旧信被水杯压住一角，稳稳地留在灯下。"
    $ last_ending = "true"
    stop music fadeout 2.0
    stop ambient fadeout 2.0
    call screen ending_card("True / 把今天说清楚")
    return

label s08_normal:
    $ current_scene = "s08_normal"
    $ current_chapter = "ch05"
    $ visited_scenes.append("s08_normal")
    scene black with dissolve
    "道别以后，我站在车站外，看着最后几滴雨落进路边的积水。旧箱子靠着腿，信封还放在口袋里。"
    "刚才的话，有些已经说清，有些还留着。下一次联系的时间，也要由我们各自确认。"
    "许澄没有替我作答。我也没有把一张旧照片，理解成她必须给我的承诺。"
    "手机亮起来。她发来一张旧照片，下面只有一行字。"
    h "这张没有拍歪。你回去以后，慢慢看。"
    p "谢谢。到家我给你发消息。"
    "我输入了完整的一句话，没有用句号代替。发送以后，又把信封按平了一点。"
    "车站关闭的时间已经写在告示上。另一些事情，今晚还没有确定。"
    "我可以继续把它们留给以后，也可以在下一次联系时，先把该说的话说出来。"
    "雨停了。这个晚上没有给出所有答案，但我们已经重新有了彼此的号码。"
    $ last_ending = "normal"
    stop music fadeout 2.0
    stop ambient fadeout 2.0
    call screen ending_card("Normal / 留给下一次的话")
    return

